In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
cancer=load_breast_cancer()

In [4]:
print(cancer.data)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [5]:
print(cancer.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [6]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
print(cancer['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [8]:
print(cancer["target_names"])

['malignant' 'benign']


In [9]:
print(cancer["feature_names"])

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [10]:
cancer['data'].shape

(569, 30)

In [12]:
df_cancer=pd.DataFrame(np.c_[cancer['data'],cancer['target']],columns=np.append(cancer['feature_names'],['target']))

In [14]:
df_cancer.sample(20)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
432        20.18         19.54          133.80     1250.0          0.11330   
167        16.78         18.80          109.30      886.3          0.08865   
375        16.17         16.07          106.30      788.5          0.09880   
199        14.45         20.22           94.49      642.7          0.09872   
519        12.75         16.70           82.51      493.8          0.11250   
43         13.28         20.28           87.32      545.2          0.10410   
31         11.84         18.70           77.93      440.6          0.11090   
275        11.89         17.36           76.20      435.6          0.12250   
303        10.49         18.61           66.86      334.3          0.10680   
158        12.06         12.74           76.84      448.6          0.09311   
161        19.19         15.94          126.30     1157.0          0.08694   
381        11.04         14.93           70.67      372.7          0.07987   
73         13.80         15.79           90.43      584.1          0.10070   
74         12.31         16.52           79.19      470.9          0.09172   
62         14.25         22.15           96.42      645.7          0.10490   
369        22.01         21.90          147.20     1482.0          0.10630   
266        10.60         18.95           69.28      346.4          0.09688   
542        14.74         25.42           94.70      668.6          0.08275   
337        18.77         21.43          122.90     1092.0          0.09116   
444        18.03         16.85          117.50      990.0          0.08947   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
432           0.14890         0.21330              0.12590         0.1724   
167           0.09182         0.08422              0.06576         0.1893   
375           0.14380         0.06651              0.05397         0.1990   
199           0.12060         0.11800              0.05980         0.1950   
519           0.11170         0.03880              0.02995         0.2120   
43            0.14360         0.09847              0.06158         0.1974   
31            0.15160         0.12180              0.05182         0.2301   
275           0.07210         0.05929              0.07404         0.2015   
303           0.06678         0.02297              0.01780         0.1482   
158           0.05241         0.01972              0.01963         0.1590   
161           0.11850         0.11930              0.09667         0.1741   
381           0.07079         0.03546              0.02074         0.2003   
73            0.12800         0.07789              0.05069         0.1662   
74            0.06829         0.03372              0.02272         0.1720   
62            0.20080         0.21350              0.08653         0.1949   
369           0.19540         0.24480              0.15010         0.1824   
266           0.11470         0.06387              0.02642         0.1922   
542           0.07214         0.04105              0.03027         0.1840   
337           0.14020         0.10600              0.06090         0.1953   
444           0.12320         0.10900              0.06254         0.1720   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
432                 0.06053  ...          25.07           146.00      1479.0   
167                 0.05534  ...          26.30           130.70      1260.0   
375                 0.06572  ...          19.14           113.10       861.5   
199                 0.06466  ...          30.12           117.90      1044.0   
519                 0.06623  ...          21.74            93.63       624.1   
43                  0.06782  ...          28.00           113.10       907.2   
31                  0.07799  ...          28.12           119.40       888.7   
275                 0.05875  ...          18.99            79.46       472.4   
303                 0.06600 

# Visualising the data
1. Pair plot
2. Count Plot
3. Scatter Plot