In [1]:
print("hello machine learning")

hello machine learning


In [12]:
import tensorflow as tf

In [10]:
! pip install tensorflow

In [13]:
tf.__version__

'2.15.0'

In [14]:
str= tf.Variable("This is string",tf.string)

In [15]:
str

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is string'>

In [18]:
tf.rank(str)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [20]:
arr1=tf.Variable(["a1","a2","a3"],tf.string)

In [21]:
tf.rank(arr1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
arr2 = tf.Variable([["a1","a2","a3"],["a4","a5","a6"]],tf.string)

In [23]:
tf.rank(arr2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [25]:
arr2.shape

TensorShape([2, 3])

In [26]:
arr1.shape

TensorShape([3])

In [32]:
tensor_1=tf.zeros([2,2,2])
tensor_1

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)>

In [33]:
reshaped_tensor_1=tf.reshape(tensor_1,[8])
reshaped_tensor_1

<tf.Tensor: shape=(8,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

# Rank: number of dimensions involved in a tensor.