Data Wrangling

In [5]:
import pandas as pd

In [6]:
train_titanic=pd.read_csv("./titanic/train.csv")

In [7]:
train_titanic.sample(5)

PassengerId  Survived  Pclass                                   Name  \
483          484         1       3                 Turkula, Mrs. (Hedwig)   
38            39         0       3     Vander Planke, Miss. Augusta Maria   
545          546         0       1           Nicholson, Mr. Arthur Ernest   
742          743         1       1  Ryerson, Miss. Susan Parker "Suzette"   
701          702         1       1       Silverthorne, Mr. Spencer Victor   

        Sex   Age  SibSp  Parch    Ticket      Fare            Cabin Embarked  
483  female  63.0      0      0      4134    9.5875              NaN        S  
38   female  18.0      2      0    345764   18.0000              NaN        S  
545    male  64.0      0      0       693   26.0000              NaN        S  
742  female  21.0      2      2  PC 17608  262.3750  B57 B59 B63 B66        C  
701    male  35.0      0      0  PC 17475   26.2875              E24        S

In [8]:
train_titanic.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [9]:
train_titanic.shape

(891, 12)

In [10]:
train_titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [11]:
train_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [12]:
train_titanic.iloc[1:7]
df=train_titanic

You want to select DataFrame rows based on some condition.

In [13]:
df[df['Sex']=='female'].sample(7)

PassengerId  Survived  Pclass  \
697          698         1       3   
610          611         0       3   
184          185         1       3   
11            12         1       1   
865          866         1       2   
328          329         1       3   
290          291         1       1   

                                                  Name     Sex   Age  SibSp  \
697                   Mullens, Miss. Katherine "Katie"  female   NaN      0   
610  Andersson, Mrs. Anders Johan (Alfrida Konstant...  female  39.0      1   
184                Kink-Heilmann, Miss. Luise Gretchen  female   4.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
865                           Bystrom, Mrs. (Karolina)  female  42.0      0   
328     Goldsmith, Mrs. Frank John (Emily Alice Brown)  female  31.0      1   
290                       Barber, Miss. Ellen "Nellie"  female  26.0      0   

     Parch  Ticket     Fare Cabin Embarked  
697      0   35852   7.7333   NaN        Q  
610      5  347082  31.2750   NaN        S  
184      2  315153  22.0250   NaN        S  
11       0  113783  26.5500  C103        S  
865      0  236852  13.0000   NaN        S  
328      1  363291  20.5250   NaN        S  
290      0   19877  78.8500   NaN        S

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [15]:
df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [16]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [17]:
df["Survived"].unique()

array([0, 1])

In [18]:
df["Pclass"].unique()

array([3, 1, 2])

In [19]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [20]:
temp_df=df
temp_df["Sex"]=df["Sex"].replace("male","men")

In [21]:
temp_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris     men  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry     men  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas     men  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell     men  26.0      0   
890                                Dooley, Mr. Patrick     men  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [22]:
temp_df["Sex"].value_counts()

Sex
men       577
female    314
Name: count, dtype: int64

In [23]:
# only male
df.groupby("Sex").mean(numeric_only=True)

PassengerId  Survived    Pclass        Age     SibSp     Parch  \
Sex                                                                      
female   431.028662  0.742038  2.159236  27.915709  0.694268  0.649682   
men      454.147314  0.188908  2.389948  30.726645  0.429809  0.235702   

             Fare  
Sex                
female  44.479818  
men     25.523893

Handling numeric data

In [24]:
from sklearn.preprocessing import MinMaxScaler
min_max=MinMaxScaler()


In [30]:
print(df['Fare'].values)

[  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55     8.05    31.275    7.8542  16.
  29.125   13.      18.       7.225   26.      13.       8.0292  35.5
  21.075   31.3875   7.225  263.       7.8792   7.8958  27.7208 146.5208
   7.75    10.5     82.1708  52.       7.2292   8.05    18.      11.2417
   9.475   21.       7.8958  41.5792   7.8792   8.05    15.5      7.75
  21.6792  17.8     39.6875   7.8     76.7292  26.      61.9792  35.5
  10.5      7.2292  27.75    46.9      7.2292  80.      83.475   27.9
  27.7208  15.2458  10.5      8.1583   7.925    8.6625  10.5     46.9
  73.5     14.4542  56.4958   7.65     7.8958   8.05    29.      12.475
   9.       9.5      7.7875  47.1     10.5     15.85    34.375    8.05
 263.       8.05     8.05     7.8542  61.175   20.575    7.25     8.05
  34.6542  63.3583  23.      26.       7.8958   7.8958  77.2875   8.6542
   7.925    7.8958   7.65     7.775    7.8958  24.15    52.      14.4542
  

In [32]:

res=min_max.fit_transform(df['Fare'].values.reshape(-1,1))

In [33]:
res

array([[0.01415106],
       [0.13913574],
       [0.01546857],
       [0.1036443 ],
       [0.01571255],
       [0.0165095 ],
       [0.10122886],
       [0.04113566],
       [0.02173075],
       [0.05869429],
       [0.03259623],
       [0.05182215],
       [0.01571255],
       [0.06104473],
       [0.01533038],
       [0.03122992],
       [0.05684821],
       [0.02537431],
       [0.03513366],
       [0.01410226],
       [0.05074862],
       [0.02537431],
       [0.01567195],
       [0.06929139],
       [0.04113566],
       [0.06126432],
       [0.01410226],
       [0.51334181],
       [0.01537917],
       [0.01541158],
       [0.0541074 ],
       [0.28598956],
       [0.01512699],
       [0.02049464],
       [0.16038672],
       [0.10149724],
       [0.01411046],
       [0.01571255],
       [0.03513366],
       [0.02194234],
       [0.01849397],
       [0.04098927],
       [0.01541158],
       [0.08115719],
       [0.01537917],
       [0.01571255],
       [0.03025399],
       [0.015